FROM directus/directus:latest

# Environment Variables
ARG SECRET
ARG ADMIN_EMAIL
ARG ADMIN_PASSWORD
ARG DB_CLIENT
ARG DB_HOST
ARG DB_PORT
ARG DB_DATABASE
ARG DB_USER
ARG DB_PASSWORD
ARG WEBSOCKETS_ENABLED
ARG PUBLIC_URL

ENV SECRET=$SECRET
ENV ADMIN_EMAIL=$ADMIN_EMAIL
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV DB_CLIENT=$DB_CLIENT
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_DATABASE=$DB_DATABASE
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV WEBSOCKETS_ENABLED=$WEBSOCKETS_ENABLED
ENV PUBLIC_URL=$PUBLIC_URL

# Expose the port Directus will run on
EXPOSE 8055
# Initialize the database and start Directus
CMD ["sh", "-c", "npx directus bootstrap && npx directus start"]