version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: 'SuperSecureRandomKey123!@#'
      ADMIN_EMAIL: 'root@root.com'
      ADMIN_PASSWORD: '12root34'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: 'true'
      PUBLIC_URL: 'https://naturaonecoat-cc85b1fdbbef.herokuapp.com'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:3000,https://naturaonecoat.vercel.app/'
      CORS_METHODS: 'GET,POST,PATCH,PUT,DELETE,OPTIONS'
      CORS_HEADERS: 'Content-Type,Authorization'
      CORS_CREDENTIALS: 'true'
